name: Package
on:
  pull_request:
  push:
    branches:
      - master
  release:
  workflow_dispatch:

jobs:
  Chromium:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/upload-artifact@v2
        with:
          name: Chromium
          path: |
            assets/
            css/
            html/
            img/
            js/
            LICENSE
            manifest.json

  Firefox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/upload-artifact@v2
        with:
          name: Firefox
          path: |
            assets/
            css/
            html/
            img/
            js/
            LICENSE
            manifest.json
