name: Release
on:
  pull_request:
  push:
    branches:
      - master
  release:

jobs:
  cws:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fix links
        run: |
          sed -i -E '/<!-- DEV /d' html/popup.html
          sed -i -E '/<!-- AMO /d' html/popup.html
          sed -i -E 's/<!-- CWS (.*) -->/\1/' html/popup.html

      - uses: actions/upload-artifact@v2
        with:
          name: CWS.zip
          path: |
            assets/
            css/
            html/
            img/
            js/
            LICENSE
            manifest.json

  amo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fix links
        run: |
          sed -i -E '/<!-- DEV /d' html/popup.html
          sed -i -E '/<!-- CWS /d' html/popup.html
          sed -i -E 's/<!-- AMO (.*) -->/\1/' html/popup.html

      - uses: actions/upload-artifact@v2
        with:
          name: AMO.zip
          path: |
            assets/
            css/
            html/
            img/
            js/
            LICENSE
            manifest.json
